# Generated by Django 4.0.2 on 2022-02-23 06:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Firstname')),
                ('last_name', models.CharField(max_length=50, verbose_name='Firstname')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Product Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Unit Price')),
                ('quantity', models.PositiveIntegerField(verbose_name='Product Quantity')),
                ('sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='Stock Keeping Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Werehouse Name')),
                ('location', models.CharField(max_length=255, verbose_name='Werehouse Locations')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255, verbose_name='Product SHipment Distination')),
                ('quantity', models.PositiveIntegerField(verbose_name='Shipped Product Quantity')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.product')),
            ],
        ),
    ]
